name: Appium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Node.js & Appium
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g appium
      - run: appium --version

      - name: Start Appium Server
        run: appium --log-level error &
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Start Android Emulator
        run: |
          echo "Installing system images..."
          sdkmanager --install "system-images;android-30;default;x86_64"

          echo "Creating AVD..."
          avdmanager create avd -n test_emulator -k "system-images;android-30;default;x86_64" --device "pixel"

          echo "Starting Emulator..."
          nohup $ANDROID_HOME/emulator/emulator -avd test_emulator -no-audio -no-window -gpu off &

          echo "Waiting for emulator to boot..."
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

      - name: Run Appium Tests
        run: ./gradlew test

      - name: Stop Appium Server
        run: pkill -f appium
