name: Appium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java 17 (for Appium)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install JAXB Dependencies for Java 11+
        run: |
          # Manually download and install JAXB API and runtime jars (version 2.3.1)
          wget https://repo1.maven.org/maven2/org/glassfish/jaxb/jaxb-api/2.3.1/jaxb-api-2.3.1.jar -P /tmp
          wget https://repo1.maven.org/maven2/org/glassfish/jaxb/jaxb-runtime/2.3.1/jaxb-runtime-2.3.1.jar -P /tmp

          # Add to classpath
          export CLASSPATH=$CLASSPATH:/tmp/jaxb-api-2.3.1.jar:/tmp/jaxb-runtime-2.3.1.jar
          echo "JAXB dependencies added to the classpath"

      - name: Install Node.js & Appium
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g appium
      - run: appium --version

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Install Android Emulator
        run: |
          export ANDROID_HOME=/usr/local/lib/android/sdk
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export PATH=$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH

          echo "Installing required Android components..."
          sdkmanager --install "platform-tools" "platforms;android-30" "emulator" "system-images;android-30;default;x86_64"

      - name: Verify Emulator Installation
        run: |
          ls -la $ANDROID_HOME/emulator || echo "Emulator directory not found!"
          ls -la $ANDROID_HOME/platform-tools || echo "Platform-tools directory not found!"

      - name: Create & Start Emulator
        run: |
          export ANDROID_HOME=/usr/local/lib/android/sdk
          export PATH=$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH

          echo "Creating AVD..."
          echo "no" | avdmanager create avd -n test_emulator -k "system-images;android-30;default;x86_64" --device "pixel" --force

          echo "Verifying AVD list..."
          emulator -list-avds || echo "No AVDs found!"

          echo "Starting Emulator..."
          nohup $ANDROID_HOME/emulator/emulator -avd test_emulator -no-audio -no-window -gpu off &

          echo "Waiting for emulator to boot..."
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
          echo "Emulator is ready!"

      - name: Start Appium Server
        run: appium --log-level error &

      - name: Run Appium Tests
        run: ./gradlew test

      - name: Stop Appium Server & Emulator
        run: |
          pkill -f appium
          adb emu kill
