name: Appium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK Command-line Tools
        run: |
          # Download and unzip the latest command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-12266719_latest.zip -P /tmp
          unzip -o /tmp/commandlinetools-linux-12266719_latest.zip -d /usr/local/lib/android/sdk
          # Accept licenses and install SDK components
          yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "emulator" "system-images;android-30;default;x86_64"

      - name: Set Environment Variables
        run: |
          export ANDROID_HOME=/usr/local/lib/android/sdk
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$PATH
          echo "ANDROID_HOME is set to $ANDROID_HOME"
          echo "PATH is set to $PATH"  # Ensure that the path contains the cmdline-tools directory

      - name: Verify if avdmanager is available
        run: |
          which avdmanager || echo "avdmanager not found in path"
          /usr/local/lib/android/sdk/cmdline-tools/latest/bin/avdmanager --version || echo "avdmanager is not working"

      - name: Create & Start Emulator
        run: |
          /usr/local/lib/android/sdk/cmdline-tools/latest/bin/avdmanager create avd -n test_emulator -k "system-images;android-30;default;x86_64" --device "pixel" --force
          emulator -list-avds || echo "No AVDs found!"
          nohup $ANDROID_HOME/emulator/emulator -avd test_emulator -no-audio -no-window -gpu off &
          echo "Waiting for emulator to boot..."
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
          echo "Emulator is ready!"

      - name: Start Appium Server
        run: appium --log-level error &

      - name: Run Appium Tests
        run: ./gradlew test

      - name: Stop Appium Server & Emulator
        run: |
          pkill -f appium
          adb emu kill

      - name: Stop Appium Server & Emulator
        run: |
          pkill -f appium
          adb emu kill
