name: Appium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK Command-line Tools
        run: |
          export ANDROID_HOME=/usr/local/lib/android/sdk
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$PATH
          
          # Ensure directories exist
          mkdir -p ~/.android/avd
          
          # Persist environment variables for later steps
          echo "export ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "export PATH=$PATH" >> $GITHUB_ENV
          
          # Download and install command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-12266719_latest.zip -P /tmp
          unzip -o /tmp/commandlinetools-linux-12266719_latest.zip -d $ANDROID_HOME
          
          # Install required SDK packages
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "emulator" "system-images;android-30;default;x86_64"
          
          # Accept licenses
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          
          # Verify installation
          which adb || echo "adb not found"
          which avdmanager || echo "avdmanager not found"
          which emulator || echo "emulator not found"

      - name: Create Emulator AVD
        run: |
          source $GITHUB_ENV
          
          echo "Checking AVD location..."
          ls -l ~/.android/avd || echo "AVD directory is missing!"

          # Ensure the AVD exists before trying to start it
          if ! $ANDROID_HOME/emulator/emulator -list-avds | grep -q "test_emulator"; then
            echo "Creating AVD: test_emulator"
            echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd \
              -n test_emulator -k "system-images;android-30;default;x86_64" --device "pixel" --force
          else
            echo "AVD already exists!"
          fi
          
          # Confirm AVD creation
          echo "Available AVDs after creation:"
          $ANDROID_HOME/emulator/emulator -list-avds

      - name: Start Emulator
        run: |
          source $GITHUB_ENV

          echo "Checking AVDs before starting..."
          $ANDROID_HOME/emulator/emulator -list-avds

          if ! $ANDROID_HOME/emulator/emulator -list-avds | grep -q "test_emulator"; then
            echo "ERROR: test_emulator not found!"
            exit 1
          fi
          
          nohup $ANDROID_HOME/emulator/emulator -avd test_emulator \
            -no-audio -no-window -gpu swiftshader_indirect \
            -no-boot-anim -no-snapshot-save -memory 4096 -cores 2 &

          echo "Waiting for emulator to boot..."
          boot_complete=false
          for i in {1..60}; do
            boot_status=$(adb shell getprop sys.boot_completed 2>/dev/null)
            if [[ "$boot_status" == "1" ]]; then
              boot_complete=true
              break
            fi
            sleep 2
          done

          if [[ "$boot_complete" == "true" ]]; then
            echo "Emulator is ready!"
            adb devices
          else
            echo "Emulator failed to start in time."
            exit 1
          fi

      - name: Start Appium Server
        run: appium --log-level error &

      - name: Run Appium Tests
        run: ./gradlew test

      - name: Stop Appium Server & Emulator
        run: |
          pkill -f appium
          adb emu kill
